# Image: applyfmsec/cloudcvcsec-tests-cvc

FROM applyfmsec/cloudcvcsec

USER root
COPY requirements-tests.txt .
RUN python -m pip install -r requirements-tests.txt

USER cloudcvcsec
COPY tests_cvc  /home/cloudcvcsec/tests_cvc
COPY tests_cvc_core /home/cloucvcsec/tests_cvc_core

COPY examples /home/cloudcvcsec/examples
WORKDIR /home/cloudcvcsec

CMD ["pytest", "-sv", "tests_cvc/test_cvc_performance.py"]
# ENTRYPOINT ["pytest"]

