# Image: applyfmsec/cloudcvcsec-tests-cvc

FROM applyfmsec/cloudcvcsec

USER root
COPY requirements-tests.txt .
RUN python -m pip install -r requirements-tests.txt

USER cloudcvcsec
COPY tests_cvc  /home/cloudcvcsec/tests_cvc

COPY examples /home/cloudcvcsec/examples
WORKDIR /home/cloudcvcsec

ENTRYPOINT ["pytest"]

